ARG BUILD_FROM
FROM $BUILD_FROM

MAINTAINER micmoc95 <mic.morat@gmail.com>

LABEL \
    io.hass.name="Raspberry Pi Router" \
    io.hass.description="Configure NAT between end0 and enu1" \
    io.hass.version="1.0.0" \
    io.hass.type="addon"
